### ISSUE TITLE
Fare script di bash 

### ISSUE THREAD

**Issue by DavideTedesco** [s-e-a-m/SEAM#1]
Per git pull su tutte e 4 le cartelle di s-e-a-m

**Comment by grammaton** [comment]
@s-e-a-m/tr319 ho fatto i miei compitini… aggiornate il vostro repo *SEAM* con `git pull` e poi avviate lo script con `bash seampull.sh`. 

@Velitch @ALESSANDRO12 ditemi se funziona anche sulle vostre macchine… nel caso contrario aprite un nuovo issue ed incollate il vostro messaggio d'errore.

Ajo
G

**Comment by grammaton** [comment]
@s-e-a-m/tr319 sono andato oltre… per i più pigri, o per i più nerd, ho fatto anche uno script `seamclone.sh` che fa il clone di tutti i repo collegati a *SEAM*.

Ajo
G

**Comment by Sibladosi** [comment]
cd ~/Downloads
bash temporary_spam.sh

Il giorno mar 30 apr 2019 alle ore 17:43 Giuseppe <notifications@github.com>
ha scritto:
