### ISSUE TITLE
MANIFESTO

### ISSUE THREAD

**Issue by grammaton** [s-e-a-m/SEAM#6]
C'è una bozza di manifesto, introduzione, motivazione. Se ne potrebbe discutere.

**Comment by DavideTedesco** [comment]
Ho iniziato a vedere e leggere e riscrivere un po' il testo, è da discutere il modo in cui  farlo arrivare alla conclusione finale con i 3 punti e forse, specificare meglio il processo da cui si è partiti per _sostenibilizzare_ i brani che abbiamo affrontato, rimango disponibile per una call.

**Comment by grammaton** [comment]
@DavideTedesco quando si correggono i testi è sempre meglio correggere solo gli errori piuttosto che fare copia ed incolla del testo intero altrimenti nella storia del file c'è una sostituzione completa e non si riesce a capire l'avanzamento della revisione.

**Comment by grammaton** [comment]
@DavideTedesco ho dato una revisione al manifesto, struttura e testo. Leggilo, se non ci sono grosse problematiche rinominalo (da web) `MANIFESTO.md`e poi chiudi la issue. grazie.
